//Methods

/*function Pair(ukr,eng) {
  this.ukr = ukr,
  this.eng = eng
}  

function Pusher(a,b) {
  return listArray.push(new Pair(a,b))
}
*/

/*
Pusher("стикатися з", "be facing");
Pusher("тендітний", "tiny");
Pusher("покладатися на", "rely on");
Pusher("виконати", "accomplish");
Pusher("багаторазовий", "reusable");
Pusher("підтримувати", "maintain by");
Pusher("підказка", "hint");
Pusher("шаблонний", "boilerplate");
Pusher("потворний", "ugly");
Pusher("мета, ціль", "objective");
Pusher("знайомство", "acquaintance");
Pusher("щелепно-лицевий", "maxillo-facial");
Pusher("навчання", "education");
Pusher("наступний", "upcoming");
Pusher("велика честь", "great honor");
Pusher("працівник", "employee");
Pusher("уважний", "attentive");
Pusher("безпомилковий", "inerrable");
Pusher("візуалізувати", "render");
Pusher("бути здатним", "be able");
Pusher("здатність", "ability");
Pusher("дбати", "look after");
Pusher("переглядати", "look through");
Pusher("суттєво, важливо", "essentialy");
Pusher("після завершення", "upon completion");
Pusher("застереження", "caveat");
Pusher("плутати", "confuse");
Pusher("окремий", "separate");
Pusher("властивість", "property");
Pusher("доставляти", "deliver");
Pusher("нудний", "tedious");
Pusher("доступність", "availibility");
Pusher("незмінний", "immutable");
Pusher("затримати", "teardown");
Pusher("незамінний", "indispensable");
Pusher("похідний", "derived");
Pusher("базується на", "base upon");
Pusher( "знімок", "snapshot");
Pusher("резервна копія", "backup");
Pusher( "умовний", "conditional");
Pusher("значок", "badge");
Pusher("попередньо визначений", "predefined");
Pusher("служити", "serve");
Pusher("знищувати", "destroy");
Pusher("передавати, виражати", "convey");
Pusher("нумерація сторінок", "pagination");
Pusher("забезпечувати", "provide");
Pusher("розсувний", "extensible");
Pusher("гнучкий", "flexible");
Pusher("різноманітність", "variety");
Pusher("хіба що", "unless");
Pusher("жолобок", "gutter");
Pusher("містити, вміщувати", "nest");
Pusher("видалити", "remove");
Pusher("вставити", "insert");
Pusher("охоплювати", "wrap");
Pusher("вкладка", "tab");
Pusher("дійсний", "valid");
Pusher("відображати", "display");
Pusher("погоджуватись", "submit");
Pusher("уточнювати, обумовлювати", "specify");
Pusher("вимагати", "require");
Pusher("заповнювати", "fill out");
Pusher("повідомляти", "notify");
Pusher("декілька", "multiple");
Pusher("пов'язаний", "related");
Pusher("вважати", "consider");
Pusher("допоміжний", "assistive");
Pusher("прапорець", "checkbox");
Pusher("однозначний, явний", "explicit");
Pusher("визначати", "define");
Pusher("парувати, підходити", "match");
Pusher("розмітка", "markup");
Pusher("за замовчуванням", "default");
Pusher("налаштовувати", "adjust");
Pusher("виробляти", "produce");
Pusher("підкреслювати", "emphasize");
Pusher("значно", "significantly");
Pusher("розмитий", "blur");
Pusher("розтягнений", "spread");
Pusher("зменшувати", "decrease");
Pusher("зручний", "convenient");
Pusher("протилежно, навпаки", "conversely");
Pusher("послідовно", "consistantly");
Pusher("пропонувати", "offer");
Pusher("наводити курсор", "hover");
Pusher("в лінію", "inline");
Pusher("вести себе, поводити", "behave");
Pusher("гнучкість", "flexibility");
Pusher("лежати в основі", "underlie");
Pusher("подібно до", "likewise");
Pusher("погіршення", "impairments");
Pusher("позиція", "item");
Pusher("предок, родоначальник", "ancestor");
Pusher("вниз", "downwards");
Pusher("ланцюг", "chain");
Pusher("остаточний", "ultimate");
Pusher("блокувати", "lock");
Pusher("нестача", "lack of");
Pusher("перекривання", "overlap");
Pusher("стопка, стос", "stack");
Pusher("викликати", "evoke");
Pusher("вибрати", "pick");
Pusher("відтінок", "hue");
Pusher("яскравий", "vibrant");
Pusher("проблема", "issue");
Pusher("відповідний", "respective");
Pusher("сусідній", "adjacent");
Pusher("витончений", "subtle");
Pusher("розпізнавати", "recognize");
Pusher("певний", "certain");
Pusher("насиченість", "saturation");
Pusher("підходити", "fit");
Pusher("відповідно", "respectively");
Pusher("поступовий", "gradual");
Pusher("перехід", "transition");
Pusher("зворотня риска", "backslash");
Pusher("смуга", "stripe");
Pusher("виділятися", "stand out");
Pusher("круглі дужки", "parentheses");
Pusher("масштаб", "scale");
Pusher("скошувати", "skew");
Pusher("чіткий", "crisp");
Pusher("відкликати", "recall");
Pusher("вибірковий", "optional");
Pusher("правильно", "properly");
Pusher("діапазон", "ranging");
Pusher("розігрувати", "act out");
Pusher("фрагмент", "snippet");
Pusher("блекнути", "fade");
Pusher("повторення", "iteration");
Pusher("змінювати", "alter");
Pusher("блимання", "twinkle");
Pusher("темп, курс", "rate");
Pusher("легкість", "ease");
Pusher("сповільнювати", "decelerate");
Pusher("прискорювати", "accelerate");
Pusher("сітка, решітка", "grid");
Pusher("оголошувати", "declare");
Pusher("імітувати", "mimic");
Pusher("назустріч", "towards");
Pusher("порівнювати", "compare");
Pusher("перевертати", "reverse");
Pusher("повторювати", "replicate");
Pusher("попередньо", "prior");
Pusher("жоден", "neither");
Pusher("зображати", "depict");
Pusher("хоча", "although");
Pusher("пізнавальний", "cognitive");
Pusher("неспроможність", "disability");
Pusher("безперервний, постійний", "ongoing");
Pusher("порушено", "impaired");
Pusher("керівництво(посібник)", "guidelines");
Pusher("наочний", "descriptive");
Pusher("обов'язковий", "mandatory");
Pusher("оцінювати", "appreciate");
Pusher("пустий", "blank");
Pusher("підпис", "caption");
Pusher("зайвий", "redundant");
Pusher("важливий", "neccessary");
Pusher("підсумок", "summary");
Pusher("лише, просто", "merely");
Pusher("підрозділ", "subsection");
Pusher("спокусливий", "tempting");
Pusher("вказувати", "indicate");
Pusher("особливості", "features");
Pusher("вбудований", "embedded");
Pusher("орієнтир", "landmark");
Pusher("визначення", "determing");
Pusher("автономний", "standalone");
Pusher("глава, розділ", "chapter");
Pusher("логічний", "boolean");
Pusher("увімкнути", "turn on");
Pusher("товариш, супутник", "fellow");
Pusher("двічі, вдвічі", "two-fold");
Pusher("цитата", "quote");
Pusher("недоцільний", "inexpedient");
Pusher("в той час як", "whereas");
Pusher("уява", "fancy");
Pusher("відтворити", "recreate");
Pusher("розділяти", "split up");
Pusher("повністю", "enterily");
Pusher("контрольна точка", "breakpoint");
Pusher("дивний", "weird");
Pusher("окрім", "except");
Pusher("вдумливий", "thoughtful");
Pusher("прив'язка", "tying");
Pusher("достатньо", "sufficiant");
Pusher("є власністю...", "is held by");
Pusher("розмовний", "colloquial");
Pusher("видимий", "visible");
Pusher("підхід", "approach");
Pusher("укладено", "stacked");
Pusher("покласти в", "put into");
Pusher("пропускати", "skip");
Pusher("обсяг", "scope");
Pusher("давати змогу", "enable");
Pusher("обставини", "circumstances");
Pusher("обмеження", "constraints");
Pusher("влаштовувати", "arrange");
Pusher("передбачуваний", "predictible");
Pusher("розтягувати", "stretch");
Pusher("поширюватись", "distribute");
Pusher("стискати, скорочувати", "shrink");
Pusher("вивід інформації", "output");
Pusher("попередній перегляд", "preview");
Pusher("виділяти, бронювати", "allocate");
Pusher("до цього моменту", "up to this point");
Pusher("споживати", "consume");
Pusher("зв'язок, з'єднання", "conjuction");
Pusher("простягатися", "span");
Pusher("зливатися", "merge");
Pusher("перевищувати", "exceed");
Pusher("розмірність", "dimension");
Pusher("переставляти, перегруповувати", "rearrange");
Pusher("нащадок", "descendant");
Pusher("принцип", "principle");
Pusher("оповіщення", "alert");
Pusher("значущий", "meaningful");
Pusher("невизначений", "undefined");
Pusher("а не...", "rather than");
Pusher("запасати", "store");
Pusher("крапка з комою", "semicolons");
Pusher("заява, судження", "statement");
Pusher("складатися з", "make up of");
Pusher("компенсувати", "make up for");
Pusher("призначення", "assignment");
Pusher("вирішувати", "resolve");
Pusher("користь", "sake");
Pusher("ясність", "clarity");
Pusher("частка(в діленні)", "quotient");
Pusher("збільшувати", "increment");
Pusher("зчеплення, сплетення", "concatenation");
Pusher("стережися", "watch out");
Pusher("витягувати, вилучати", "retrieve");
Pusher("поки", "while");
Pusher("ненавмисно", "unintended");
Pusher("перевизначати", "override");
Pusher("точність", "accuracy");
Pusher("припускати", "assume");
Pusher("акуратно", "neatly");
Pusher("отримувати, добиватися", "obtain");
Pusher("крах, провал", "failure");
Pusher("лаконічний", "concise");
Pusher("повноцінний", "full-fledged");
Pusher("відступати", "fallback");
Pusher("використовуючи", "utilizing");
Pusher("вузький", "narrow");
Pusher("доручати", "commiserate");
Pusher("переміщувати", "transpose");
Pusher("схильний", "tend");
Pusher("умова", "condition");
Pusher("виправляти", "fix");
Pusher("постачати", "supply");
Pusher("показник", "exponent");
Pusher("виникати", "arise");
Pusher("допускати", "suppose");
Pusher("боятися", "dread");
Pusher("відновлювати", "restore");
Pusher("розглядати", "examine");
Pusher("обмежувати", "enclose");
Pusher("наприклад", "for instance");
Pusher("надто спрощений", "oversimplified");
Pusher("може пригодитись", "might come in handy");
Pusher("звивистий, закручений", "convoluted");
Pusher("аналіз, оцінка", "evaluation");
Pusher("урізати", "truncate");
Pusher("доречний", "relevant");
Pusher("друкувати великими літерами", "capitilize");
Pusher("відчутний, матеріальний", "tangible");
Pusher("копія, двійник", "counterpart");
Pusher("тема, предмет", "topic");
Pusher("відслідковувати", "keep track");
Pusher("вирішальний", "crucial");
Pusher("стирати, викреслювати", "erase");
Pusher("недолік", "disadvantage");
Pusher("засіб, рецепт", "recipe");
Pusher("справа, випадок", "case");
Pusher("завершення, закриття", "closure");
Pusher("негайно", "immediately");
Pusher("зразок, модель", "pattern");
Pusher("милий, дотепний", "cute");
Pusher("пов'язувати", "bind");
Pusher("надавати перевагу", "prefer");
Pusher("сховище, вмістилище", "repository");
Pusher("знизитись", "decline");
Pusher("в подальшому", "further");
Pusher("недавній", "recent");
Pusher("реєструватись, записуватись", "enroll");
Pusher("новинка", "brand new");
Pusher("чудо, диво", "miracle");
Pusher("навчальна програма", "syllabus");
Pusher("розширюватись, збільшуватись", "expand");
Pusher("проміжний", "intermediate");
Pusher("взаємодіяти", "interact");
Pusher("наслідування", "emulation");
Pusher("купа, група, набір", "bunch");
Pusher("суттєвий", "substantial");
Pusher("законний", "legit");
Pusher("виражати, висловлюватись", "express");
Pusher("наполегливість", "persistance");
Pusher("багато...", "plenty of");
Pusher("виставити, піддавати", "expose");
Pusher("спокійний", "restful");
Pusher("схожості, подібності", "similarity");
Pusher("дозвіл", "permission");
Pusher("добре продуманий", "well-thought");
Pusher("придумувати", "come up");
Pusher("роздумувати, розглядати", "dissect");
Pusher("початковий", "initial");
Pusher("винищувати, руйнувати", "destroy");
Pusher("перевірка", "validation");
Pusher("невідповідність", "disperancy");
Pusher("відключати", "disable");
Pusher("затримка", "delay");
Pusher("додавати", "append");
Pusher("всеосяжний", "comprehensive");
Pusher("розгортання", "deployment");
Pusher("перекреслення", "strikethrough");
Pusher("надійне джерело", "reliable source");
Pusher("співвідношення", "ratio");
Pusher("уявити собі", "imagine");
Pusher("пропорція", "propotion");
Pusher("поширювати, поглиблювати", "extend");
Pusher("панель інструментів", "dashboard");
Pusher("спрощувати", "simplify");
Pusher("технічна підтримка", "maintanance");
Pusher("обробка", "handling");
Pusher("бути здивованим", "wonder");
Pusher("база, обгрунтування", "foundation");
Pusher("інакше", "otherwise");
Pusher("залишатися, зберігатися", "remain");
Pusher("розв'язаний", "unleashed");
Pusher("потік", "flux");
Pusher("обчислення", "computations");
Pusher("і так далі", "and so on");
Pusher("спрацьовує", "is trigerred");
Pusher("переключатися", "toggle");
Pusher("тимчасовий", "temporary");
Pusher("постійний", "constant");
Pusher("прикріплювати", "attach");
Pusher("м'який", "mellow");
Pusher("потрійний", "ternary");
Pusher("надійний", "robust");
Pusher("частково", "partially");
Pusher("передавати", "pass");
Pusher("поруч з", "next to");
Pusher("запускати", "launch");
Pusher("випередження", "advance");
Pusher("відставання", "retard");
Pusher("куди", "whither");
Pusher("посміти", "dare");
Pusher("проводити, керувати", "conduct");
Pusher("існувати", "exist");
Pusher("обробляти", "handle");
Pusher("примушувати", "enforce");
Pusher("засвідчувати", "authenticate");
Pusher("чинити опір", "fight back");
Pusher("перетворювати", "convert");
Pusher("звертатися", "call on");
Pusher("здогататися", "figure out");
Pusher("акція", "promotion");
Pusher("перевіряти", "inspect");
Pusher("припиняти", "prepend");
Pusher("чесний", "honest");
Pusher("обманювати", "deceive");
Pusher("гордість", "pride");
Pusher("оманливий", "deceptive");
Pusher("дратувати", "annoy");

Pusher("представляти щось", "present");
Pusher("представляти когось", "introduce");
Pusher("давно", "for a long time");
Pusher("кого", "whom");
Pusher("посилювати", "increase");
Pusher("чия, чия, чиє", "whose");
Pusher("покращити", "improve");
Pusher("відносини, стосунки", "relationships");
Pusher("уникати", "avoid");
Pusher("нагода", "opportunity");
Pusher("запобігати", "prevent");
Pusher("впливати", "affect");
Pusher("пояснювати", "explain");
Pusher("до шостої години", "by six");
Pusher("заробляти", "earn");
Pusher("страждати", "suffer");
Pusher("тенденція", "trend");
Pusher("вигода, користь", "benefit");
Pusher("досвід", "experience");
Pusher("розмова", "conversation");
Pusher("наслідки", "consequences");
Pusher("дозвіл", "permission");
Pusher("опинитися", "end up");
Pusher("існування", "existence");
Pusher("поширений", "common");
Pusher("сертифікат", "certification");
Pusher("зручність, комфорт", "convenience");
Pusher("клієнт", "customer");
Pusher("сумісний", "combatible");
Pusher("попит", "demand");
Pusher("недолік", "drawback");
Pusher("ефективний", "efficient");
Pusher("надавати роботу", "employ");
Pusher("обладнання", "equipment");
Pusher( "сфера, оточення", "environment");
Pusher( "задоволення", "pleasure");
Pusher("компетенція, обізнаність", "expertise");
Pusher("розшифровувати", "decrypt");
Pusher("стискати", "compress");
Pusher("підключати", "plug in");
Pusher("оновлювати", "update");
Pusher("перезавантажувти", "reboot");
Pusher( "модернізувати, покращувати", "upgrade");
Pusher("роз'єм", "port");
Pusher("апарат", "device");
Pusher("програмне забезпечення", "software");
Pusher("акустична колонка", "speaker");
Pusher("обробка даних", "data processing");
Pusher("шкідливий", "malicious");
Pusher("закладка", "bookmark");
Pusher("домен", "domain");
Pusher("миттєвий", "instant");
Pusher("безпровідний", "wireless");
Pusher("знайомий", "familiar");
Pusher("аудиторія", "audience");
Pusher("уважно слухаю", "i am all ears");
Pusher("зустріч", "appointment");
Pusher("запитувати", "ask");
Pusher("розраховувати", "count on");
Pusher("записувати", "write down");
Pusher("обдумувати це", "think it over");
Pusher("інвестиції", "investment");
Pusher("податки", "taxes");
Pusher("борг", "debt");
Pusher("загроза", "threat");
Pusher("приймати рішення", "make a decision");
Pusher("дослідження", "research");
Pusher("видання", "edition");
Pusher("тінь", "shadow");
Pusher("інформатика", "computer science");
Pusher("математика", "maths");
Pusher("ділення", "division");
Pusher("різниця", "diference");
Pusher("множення", "multiplication");
Pusher("віднімання", "subtraction");
Pusher("додавання", "addition");
Pusher("фігурні дужки", "braces");
Pusher("рівність", "equality");
Pusher("дробна точка", "decimal point");
Pusher("квадратні дужки", "square brackets");
Pusher("нерівність", "inequality");
Pusher("оцінка", "mark");
Pusher("лекція", "lecture");
Pusher("записки", "notes");
Pusher("переклад", "translation");
Pusher("крапка", "dot");
Pusher("поняття, ідея", "concept");
Pusher("відкриття", "discovery");
Pusher("висновок", "conclusion");
Pusher("заробляти на життя", "earn one's living");
Pusher("вільний час", "flexitime");
Pusher("робота на повну ставку", "full-time job");
Pusher("робота на неповну ставку", "part-time job");
Pusher("відрахування від зарплати", "pay cut");
Pusher("рід занять, професія", "occupation");
Pusher("кар'єрне просування", "promotion");
Pusher("робочі години", "working hours");
Pusher("подати док-ти на роботу", "apply for a job");
Pusher("працювати понаднормово", "work overtime");
Pusher("стажер", "apprentice");
Pusher("досвідчений працівник", "skilled worker");
Pusher("вакансія", "vacancy");
Pusher( "коротка біографія", "curriculum vitae");
Pusher("бути безробітним", "be unemployed");
Pusher("навчання, тренування", "training");
Pusher("співбесіда", "job interview");
Pusher("звільняти з роботи", "discharge");
Pusher("шукати роботу", "look for a job");
Pusher("нижче", "below");
Pusher("десь", "somewhere");
Pusher("все-одно", "anyway");
Pusher("претендувати", "claim");
Pusher("корисний", "useful");
Pusher("штучний інтелект", "artificial intelligence");
Pusher("приховувати", "hide");
Pusher("набирати номер", "dial");
Pusher("система числення", "numeral system");
Pusher("підіймати слухавку", "pick up");
Pusher("вішати слухавку", "hang up");
Pusher("перемога", "victory");
Pusher("поразка", "defeat");
Pusher("дії, вчинки", "actions");
Pusher("маршрут", "route");
Pusher("випадок", "occasion");
Pusher("шум", "noise");
Pusher("пояснення", "explanation");
Pusher("відповідальний", "responsible");
Pusher("розумний", "clever");
Pusher("талановитий", "talented");
Pusher("стабільний", "stable");
Pusher("обмежений", "limited");
Pusher("марний", "vain");
Pusher("складний", "complex");
Pusher("бажаний", "desirable");
Pusher("вигідний", "disadvatageous");
Pusher("зростаючий", "growing");
Pusher("гучний", "loud");
Pusher("безпечний", "safe");
Pusher("однаковий", "same");
Pusher("звичайний", "usual");
Pusher("повний", "complete");
Pusher("увесь", "whole");
Pusher("ймовірний", "possible");
Pusher("далекий", "far");
Pusher("точний", "certain");
Pusher("єдиний", "single");
Pusher("базовий", "basic");
Pusher("впевнений", "sure");
Pusher("спричиняти", "cause");
Pusher("відбуватися", "happen");
Pusher("володіти", "own");
Pusher("берегти", "keep");
Pusher("відрізнятися", "differ");
Pusher("встановлювати", "set");
Pusher("по четвергах", "on thursdays");
Pusher("за сніданком", "at breakfast");
Pusher("вдень", "in the afternoon");
Pusher("через день", "every other day");
Pusher("до обіду", "by lunchtime");
Pusher("через три дні", "in three days");
Pusher("до липня", "until July");
Pusher("пізніше", "afterwards");
Pusher("вночі", "at night");
Pusher("час від часу", "once in a while");
Pusher("в будні дні", "on weekdays");
Pusher("до п'ятниці", "by friday");
Pusher("в понеділок", "on monday");
Pusher("післязавтра", "day after tomorrow");
Pusher("вчасно", "in time");
Pusher("рідко", "seldom");
Pusher("позавчора", "day before yesterday");
Pusher("в теперішній час", "at present");
Pusher("на вихідних", "at the weekend");
Pusher("опівночі", "at midnight");
Pusher("опівдні", "at noon");
Pusher("позичати", "lend");
Pusher("покласти", "lay");
Pusher("шукати", "seek");
Pusher("означати", "mean");
Pusher("наперекір", "notwithstanding");
Pusher("тримати", "hold");
Pusher("в межах", "within");
Pusher("для того щоб", "in order to");
Pusher("у відповідності до", "according to");
Pusher("так як", "due to");
Pusher("де б не", "wherever");
Pusher("у випадку", "in case");
Pusher("за виключенням", "barring");
Pusher("однак", "however");
Pusher("незважаючи на", "regardless of");
Pusher("назовні", "outside");
Pusher("за межами", "beyond");
Pusher("скрізь", "throughout");
Pusher("серед", "among");
Pusher("поруч", "beside");
Pusher("як наслідок", "on account of");
Pusher("поперек", "across");
Pusher("відносно", "regarding");
Pusher("рахунок", "bill");
Pusher("завдяки", "thanks to");
Pusher("несподівано", "suddenly");
Pusher("відмінно", "perfectly");
Pusher("обережно", "cautiosly");
Pusher("однаково", "equally");
Pusher("рівномірно", "evenly");
Pusher("щоденно", "daily");
Pusher("люб'язно", "kindly");
Pusher("безсумнівіно", "doubtfully");
Pusher("очевидно", "obviously");
Pusher("охоче", "willingly");
Pusher("постійно", "constantly");
Pusher("на щастя", "fortunately");
Pusher("з надією", "hopefully");
Pusher("останнім часом", "lately");
Pusher("звичний", "customary");
Pusher("вражаючий", "impressive");
Pusher("величезний", "enormous");
Pusher("виняток", "exception");
Pusher("посилання", "refer");
Pusher("очікування", "expectation");
Pusher("постачальник", "vendor");
Pusher("прагнення", "longing");
Pusher("невдоволення", "irritation");
Pusher("нетерпеливий", "impatient");
Pusher("інтенсивний", "eager");
Pusher("збентежений", "confuse");
Pusher("стурбований", "worried");
Pusher("влучне зауваження", "witty remark");
Pusher("безглуздий", "senseless");
Pusher("даремний", "useless");
Pusher("схвалення", "acceptence");
Pusher("допитливий", "curious");
Pusher("залежний", "dependent");
Pusher("довіряти", "trust");
Pusher("вісь", "axis");
Pusher("порядок спадання", "descending order");
Pusher("знімати готівку", "take off");
Pusher("бути схожим", "take after");
Pusher("виручити", "help out");
Pusher("відрізати", "cut off");
Pusher("згадувати", "look back");
Pusher("рухатися далі", "move on");
Pusher("мати справу", "deal with");
Pusher("обговорювати", "talk over");
Pusher("відкидати", "turn down");
Pusher("пильнувати", "look out");
Pusher("дізнаватися", "find out");
Pusher("віддаватти", "give back");
Pusher("справитися", "get over");
Pusher("дорослішати", "grow up");
Pusher("з'явитися", "show up");
Pusher("ретельно вивичати", "look over");
Pusher("очікувати з нетерпінням", "look forward to");
Pusher("перетворюватися на", "turn into");
Pusher("відхиляти", "turn away");
Pusher("продовжувати", "carry on");
Pusher("натикатися", "come across");
Pusher("завершуватися", "run out");
Pusher("випускати", "let out");
Pusher("надолужувати", "catch up");
Pusher("байдикувати", "sit back");
Pusher("хизуватися", "show off");
Pusher("відбирати", "take away");
Pusher("обдзвонювати", "call around");
Pusher("переходити", "go over");
Pusher("вриватися", "break in");
Pusher("звертати увагу", "point out");
Pusher("втілити у життя", "bring to life");
Pusher("бути переконаним", "feel strongly");
Pusher("оглядатися назад", "looking backwards");
Pusher("підводити, підставляти", "let down");
Pusher("почати заново", "start over");
Pusher("стикатися з питанням", "face a question");
Pusher("зосереджуватися на", "focus on");
Pusher("учасник заходу", "attendee");
Pusher("двосторонні перемовини", "bilateral talks");
Pusher("взаєморозуміння", "mutual understanding");
Pusher("взаємна зацікавленість", "mutual interest");
Pusher("пропозиція", "proposal");
Pusher("участь", "participation");
Pusher("прояснювати", "clarify");
Pusher("глибоке розуміння", "deep understanding");
Pusher("переривати", "interrupt");
Pusher("представник", "representative");
Pusher("відхиляти пропозицію", "disapprove a proposal");
Pusher("співпрацювати", "collaborate");
Pusher("скарга", "grievance");
Pusher("приходити до висновку", "come to conclusion");
Pusher("відсутній", "absent");
Pusher("невігластво", "ignorance");
Pusher("відділяти", "sever");
Pusher("інтелект", "intelligence");
Pusher("рішучий", "aggresive");
Pusher("примітка, коментар", "annotation");
Pusher("критичне мислення", "critical thinking");
Pusher("самоук", "autodidact");
Pusher("ввідний курс", "introduction");
Pusher("вирішування задач", "problem solving");
Pusher("домовленість", "compromise");
Pusher("тісна співпраця", "close cooperation");
Pusher("неодмінно", "certainly");
Pusher("це того не варто", "it's not worth it");
Pusher("мені пора йти", "i got to go");
Pusher("взаємно", "same to you");
Pusher("вибачте що заставив чекати", "sorry to keep you waiting");
Pusher("будьте здорові", "bless you");
Pusher("жартую!", "just kidding");
Pusher("зачекайте хвилину(телефон)", "hang on a minute");
Pusher("дайте мені знати", "let me know");
Pusher("маєте хвилинку?", "have you got a minute");
Pusher("радий про це чути", "glad to hear it");
Pusher("шкода про це чути", "sorry to hear that");
Pusher("боюсь, що...", "i'm affraid that");
Pusher("на мою думку", "in my opinion");
Pusher("гарного дня", "have a nice day");
Pusher("я не згоден", "i disagree");
Pusher("працював багато", "working a lot");
Pusher("багато вчився", "studying a lot");
Pusher("я був дуже зайнятим", "i've been very busy");
Pusher("все як завжди", "same as usual");
Pusher("я на роботі", "i'm at work");
Pusher("я вдома", "i'm at home");
Pusher("близько року", "about a year");
Pusher("трохи більше двох років", "just over two years");
Pusher("ще один місяць", "another month");
Pusher("незахищенність", "exposure");
Pusher("забов'язаність", "commitment");
Pusher("поправка", "amendment");
Pusher("поняття", "notion");
Pusher("мабуть", "apparently"); 
Pusher("обширний", "vast");
Pusher("законодавство", "legislation");
Pusher("добробут", "welfare");
Pusher("ступінь", "extent");
Pusher("виявляти", "reveal");
Pusher("дохід", "revenue");
Pusher("оповідач", "narrator");
Pusher("бідність", "poverty");
Pusher("переповнюваити", "overhelm");
*/